### ISSUE TITLE
High-level integration

### ISSUE THREAD

**Issue by SoftwareGuy** [nxrighthere/ENet-CSharp#28]
Hi there.

Firstly, thank you for writing a easy-to-understand wrapper with great documentation.

I'm currently using this wrapper to plug ENET into Mirror HLAPI (yes, that one that ships with Telepathy). So far the server instance boots and starts listening for connections correctly. As you can probably see on [my GitHub](https://github.com/SoftwareGuy/Ignorance), I've made a very good amount of progress plugging it into Mirror as a TransportLayer. I have been able to make a server listen and receive the connection/disconnection events, but on the client side not so much. I've got some issues that I'd like your assistance with as I'm sure we can resolve them, I just need some pointing in the right direction.

**Let's start with the first problem:**

Mirror uses integers (Int32) for connection IDs and whatnot. It seems your wrapper returns uint32 for the connection ID (I assume that's the peer ID)? In addition, this uint32 seems to be very random and not an ID like "1" or "4". Let's put it into context with an example from my project:

```Ignorance rUDP Transport ClientGetNextMessage() connect with peer ID 1747586127, IP 127.0.0.1```

That peer ID seems to be a endless loop, in the sense, that it will go to some huge number that the Int32 conversion will fail causing this when using `Convert.ToInt32(peer.ID)`:

```
OverflowException: Value was either too large or too small for an Int32.
System.Convert.ToInt32 (System.UInt32 value) (at <cfc149f8218b496788d8493c87de777a>:0)
```
I have also noticed the PeerID will go from positive to negative (overflow?) and then rinse and repeat. I don't know exactly how ENet does its Peer IDs, is it randomly generating numbers and picking one at will, or is it reading a "dirty" memory address? Is there a way to get int32 peer IDs rather than uint32s?

Or perhaps I shouldn't use peerID and use some sort of tracking mechanism to start connections from 0? 

**Second problem:**

When I'm polling the client for new messages, I get this error message:

```
InvalidOperationException: Host not created
```

This error points to the `client.Service()` function at line 103 inside my IgnoranceTransport.cs file inside my git, or you can see the snippet below.

```csharp
        /// <returns></returns>
        public bool ClientGetNextMessage(out TransportEvent transportEvent, out byte[] data)
        {
            transportEvent = TransportEvent.Disconnected;
            data = null;

            // Create a placeholder variable for the incoming ENetEvent that will be emitted by ENet Wrapper.
            Event ENetEvent;

            // Get the next message...
            client.Service(0, out ENetEvent);
```
 I have already called client.Create() before hand like so:
```csharp
private Host client;

        public void ClientConnect(string address, int port)
        {
            client = new Host(); // <- set up a new Host object

            clientAddress = new Address() { Port = Convert.ToUInt16(port) }; // setup port num
            clientAddress.SetHost(address); // set the host to connect to, this client is not a server.

            // Create the client.
            client.Create();
            // Connect the client to the server.
            clientPeer = client.Connect(clientAddress);
}
```
This is literally the same thing that I copied and pasted from the Server routines that spawn the server for listening. However, I must use the SetHost() thing to point the clientAddress to the right host (otherwise I fear that it'll try to connect to loopback). It just doesn't seem to want to properly initialize. On a server instance, it does receive a EventType.Connect and then a EventType.Disconnect. So it is at least trying to do something, but I don't understand why it's just throwing in the towel.

I look forward to hearing your thoughts and possible solutions.

**Comment by SoftwareGuy** [comment]
Okay, can you please tell me what the ideal position in the execution order is for the ENet Wrapper? Is it recommended to have it run before the start of any other scripts?

I will look into the peer IDs and such tomorrow. Please keep the ticket open until we resolve this.

**Comment by SoftwareGuy** [comment]
Alright, I was able to successfully fix the client Host not created issue. And I also have the client transmitting data over reliable channel to the server. However, when I go to grab the data being firehosed towards the server,  it seems that from inside Unity we cannot use Packet.CopyTo() as this throws a Access Violation which Unity catches and faithfully goes down with the crash while displaying the Bug Report box:

```
Unity Editor [version: Unity 2017.4.12f1_b582b87345b1]

enet.dll caused an Access Violation (0xc0000005)
  in module enet.dll at 0033:400b2806.

Error occurred at 2018-11-04_123404.
C:\UnityLTS2017.4\Editor\Unity.exe, run by Matt.
38% memory in use.
16327 MB physical memory [10057 MB free].
17351 MB paging file [8525 MB free].
134217728 MB user address space [134210140 MB free].
Read from location 00000018 caused an access violation.
```
The code that triggers this is as follows:
```csharp
byte[] newDataPacketContents = new byte[incomingEvent.Packet.Length];
incomingEvent.Packet.CopyTo(newDataPacketContents); // <- Access Violation!
Debug.LogFormat("Received: {0}", BitConverter.ToString(newDataPacketContents));
```

As you can probably tell, this code is essential for retrieving the data being received so Mirror, the HLAPI can process it. Is there a way we could make a property in ENet.cs that would allow us to get the packet data directly and also have CopyTo as well?

We're so close to having this as a functional transport and I'd hate to be let down by this crash.

**Comment by nxrighthere** [comment]
>  it seems that from inside Unity we cannot use Packet.CopyTo() as this throws a Access Violation

Your code is incorrect. You are destroying packets where you shouldn't. Move the line 201 -> 193 before breaking the switch, and same with line 377 -> 369.

> We need to find a workaround, hopefully in the ENet Wrapper.

The wrapper speaks for itself. It's wrapping low-level native functions. The thing that you are modifying stands as transport-agnostic, so fix stuff right where it should be fixed, logically.

**Comment by nxrighthere** [comment]
Two more things.

Instead of duplicating functions you can use switch cases like this:
```csharp
case EventType.Disconnect: case EventType.Timeout:
	Debug.Log("This event is " + (incomingEvent.Type == EventType.Disconnect ? "disconnect" : "timeout"));
	...
```

Don't flush the host everywhere. Let the service to do its job.

**Comment by wobes1** [comment]
Hi there.

Do we have to use Flush every time after Service call?

**Comment by nxrighthere** [comment]
Nope, the service automatically sends all queued packets. It makes sense to flush the host when the service is no longer in a loop like when you shutdown the server for example.

**Comment by SoftwareGuy** [comment]
I applied the fix that you mentioned nxrighthere and I'm still experiencing the crashes in both Unity Editor and compiled Unity Runtime. I have pushed the updated transport code to my git, could you please take a look and see if I've moved the code around correctly?

The error is pretty much the same as last time:
```
enet.dll caused an Access Violation (0xc0000005)
  in module enet.dll at 0033:66a02806.

Error occurred at 2018-11-05_121416.
D:\GameDev\_Builds\aaa.exe, run by Matt.
45% memory in use.
16327 MB physical memory [8946 MB free].
17351 MB paging file [6474 MB free].
134217728 MB user address space [134212941 MB free].
Read from location 00000018 caused an access violation.

Context:
RDI:    0x00000000  RSI: 0x00000000  RAX:   0xff76d5a0
RBX:    0x96d2f3b0  RCX: 0xff7700c0  RDX:   0x00000000
RIP:    0x66a02806  RBP: 0x00000000  SegCs: 0x00000033
EFlags: 0x00010297  RSP: 0x96d2e490  SegSs: 0x0000002b
R8:    0x00000000  R9: 0xff765ad0  R10:   0x00000005
R11:    0x66a027c0  R12: 0xff7700c0  R13:   0x8249f450
R14:    0x00000000  R15: 0xff7700c0
```

**Comment by nxrighthere** [comment]
Can you show me please the full crash log with stack trace?

**Comment by SoftwareGuy** [comment]
Sure, I'll upload that when i get to my workstation tomorrow morning.

**Comment by wobes1** [comment]
> Nope, the service automatically sends all queued packets. It makes sense to flush the host when the service is no longer in a loop like when you shutdown the server for example.

Much appreciate that.

**Comment by SoftwareGuy** [comment]
Alright, here's part 1 of what you wanted me to upload, nx. It's the crash dump and error log.
I will upload the project to my web server and you can get it from there in the next comment.

[Crash_2018-11-06_110500.zip](https://github.com/nxrighthere/ENet-CSharp/files/2551232/Crash_2018-11-06_110500.zip)

**Comment by SoftwareGuy** [comment]
Here's the project and built binary.

Project itself, includes Mirror, Enet wrapper and Ignorance. No built binaries:
```
https://1drv.ms/u/s!AgR6Upd63k5QoToEsMjuOEhNwAr-
```
Compiled build only, built freshly from the project files above. Development build and PDB files are present too. (10MB+)
```
https://1drv.ms/u/s!AgR6Upd63k5QoTtBScSGKdlApLva
```
Using OneDrive because I forgot I have no FTP client and can't be arsed to install one right now. Hopefully OneDrive won't be a bitch for you.

**Comment by nxrighthere** [comment]
The crash report from the editor please, the standalone doesn't contain much information, unfortunately. You can find editor's crash report in Win+R -> %temp%\Unity\Editor\Crashes

**Comment by nxrighthere** [comment]
> NULL_CLASS_PTR_READ_c0000005_enet.dll!Unknown
>
> 0x0000000066A02806 (enet) enet_peer_send
> 0x00000000376AB839 (Mono JIT Code) (wrapper managed-to-native) ENet.Native:enet_peer_send (intptr,byte,intptr)

You didn't create the packet and trying to send a non-existent native struct at line 202.

I'm going to add some checks to avoid such issue and throw an exception.

**Comment by nxrighthere** [comment]
Added in https://github.com/nxrighthere/ENet-CSharp/commit/154e0cf83e297dd143064d0bce3e73f2e54c2226 commit.

**Comment by SoftwareGuy** [comment]
**HOLY SHIT. THANK YOU NX!**
Now it's working. I wouldn't have done this without your persistence and continued guidance. Now both the client and server are talking to each other. I cannot believe I missed that Packet creation step... man, I feel dumb!

I'll do some final tests before wrapping it up and tidying it up - I'll close the issue ticket as soon as it finishes the tests.

**Comment by nxrighthere** [comment]
Sure, tell me how it works for ya when you're done.

**Comment by SoftwareGuy** [comment]
Well, after a stress test of about 18k packets going back and forth between localhost server and client, there were less than 100 lost packets. When doing some math, that's like 0.3% or something if my maths is wrong. This was on reliable UDP mode of course. Tests using unreliable sequenced where not performed.

So I think we're good to close this for now, and we can revisit it if there's any major problems again.

Thank you again for your assistance. I seriously can't believe it's all working and a good chunk of frustration was solved due to spotting my not initializing the packet error.

**Comment by nxrighthere** [comment]
Glad to hear. Don't forget to utilize channels for better latencies and independent sequencing for packets. Try to avoid using reliable packets when it's possible, unreliable is faster.
